2019-03-13 16:59:46.152747: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 16:59:46.154747: wfastcgi.py 3.0.0 initialized
2019-03-13 17:01:28.146082: wfastcgi.py exiting because web.config has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:01:28.146082: Running on_exit tasks
2019-03-13 17:02:05.530106: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:02:05.532102: wfastcgi.py 3.0.0 initialized
2019-03-13 17:05:45.324775: wfastcgi.py exiting because web.config has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:05:45.324775: Running on_exit tasks
2019-03-13 17:06:11.036668: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:06:11.052296: wfastcgi.py 3.0.0 initialized
2019-03-13 17:07:20.560145: wfastcgi.py exiting because my_app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:07:20.561147: Running on_exit tasks
2019-03-13 17:07:29.816147: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:07:29.818150: wfastcgi.py 3.0.0 initialized
2019-03-13 17:08:20.159516: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:08:20.159516: wfastcgi.py 3.0.0 initialized
2019-03-13 17:09:04.822830: wfastcgi.py exiting because my_app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:09:04.822830: Running on_exit tasks
2019-03-13 17:09:10.477332: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:09:10.478350: wfastcgi.py 3.0.0 initialized
2019-03-13 17:09:23.118400: wfastcgi.py exiting because my_app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:09:23.118400: Running on_exit tasks
2019-03-13 17:10:27.315359: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:10:27.315359: wfastcgi.py 3.0.0 initialized
2019-03-13 17:10:38.723974: wfastcgi.py exiting because web.config has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:10:38.723974: Running on_exit tasks
2019-03-13 17:10:55.796982: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:10:55.796982: wfastcgi.py 3.0.0 initialized
2019-03-13 17:21:24.978694: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-13 17:21:24.979694: Running on_exit tasks
2019-03-13 17:21:24.980695: wfastcgi.py 3.0.0 closed
2019-03-13 17:22:46.756724: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:22:46.772349: wfastcgi.py 3.0.0 initialized
2019-03-13 17:23:48.482554: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:23:48.483554: Running on_exit tasks
2019-03-13 17:24:27.908107: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:24:27.908107: wfastcgi.py 3.0.0 initialized
2019-03-13 17:26:36.198569: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:26:36.198569: wfastcgi.py 3.0.0 initialized
2019-03-13 17:33:00.355055: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-13 17:33:00.355055: Running on_exit tasks
2019-03-13 17:33:00.355055: wfastcgi.py 3.0.0 closed
2019-03-13 17:36:53.892431: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:36:53.894431: wfastcgi.py 3.0.0 initialized
2019-03-13 17:37:25.321886: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:37:25.322886: Running on_exit tasks
2019-03-13 17:37:32.972625: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:37:32.974632: wfastcgi.py 3.0.0 initialized
2019-03-13 17:38:01.684091: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:38:01.685090: Running on_exit tasks
2019-03-13 17:38:08.472352: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:38:08.487912: wfastcgi.py 3.0.0 initialized
2019-03-13 17:40:54.429107: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:40:54.479168: Running on_exit tasks
2019-03-13 17:41:08.044317: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:41:08.044317: wfastcgi.py 3.0.0 initialized
2019-03-13 17:41:29.896476: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:41:29.896476: Running on_exit tasks
2019-03-13 17:41:39.137532: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:41:39.137532: wfastcgi.py 3.0.0 initialized
2019-03-13 17:41:54.758333: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:41:54.758333: Running on_exit tasks
2019-03-13 17:42:22.664775: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:42:22.664775: wfastcgi.py 3.0.0 initialized
2019-03-13 17:42:51.314357: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:42:51.314357: Running on_exit tasks
2019-03-13 17:42:59.998589: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:42:59.998589: wfastcgi.py 3.0.0 initialized
2019-03-13 17:43:55.557161: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:43:55.557161: Running on_exit tasks
2019-03-13 17:44:06.133420: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:44:06.133420: wfastcgi.py 3.0.0 initialized
2019-03-13 17:44:46.957191: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:44:46.957191: Running on_exit tasks
2019-03-13 17:44:54.874794: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:44:54.890418: wfastcgi.py 3.0.0 initialized
2019-03-13 17:45:15.190933: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:45:15.190933: Running on_exit tasks
2019-03-13 17:45:27.636289: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:45:27.636289: wfastcgi.py 3.0.0 initialized
2019-03-13 17:46:01.171200: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:46:01.172200: Running on_exit tasks
2019-03-13 17:46:16.637304: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:46:16.637304: wfastcgi.py 3.0.0 initialized
2019-03-13 17:47:26.293031: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:47:26.294031: Running on_exit tasks
2019-03-13 17:47:34.755295: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:47:34.755295: wfastcgi.py 3.0.0 initialized
2019-03-13 17:47:52.347154: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-13 17:47:52.347154: Running on_exit tasks
2019-03-13 17:51:28.698435: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-13 17:51:28.700394: wfastcgi.py 3.0.0 initialized
2019-03-13 18:00:12.875621: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-13 18:00:12.875621: Running on_exit tasks
2019-03-13 18:00:12.875621: wfastcgi.py 3.0.0 closed
2019-03-14 12:57:39.436896: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 12:57:39.436896: wfastcgi.py 3.0.0 initialized
2019-03-14 13:02:47.148800: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-14 13:02:47.148800: Running on_exit tasks
2019-03-14 13:02:47.148800: wfastcgi.py 3.0.0 closed
2019-03-14 13:11:55.017310: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:11:55.032906: wfastcgi.py 3.0.0 initialized
2019-03-14 13:15:23.809620: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:15:23.809620: wfastcgi.py 3.0.0 initialized
2019-03-14 13:17:15.408966: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 13:17:15.409965: Running on_exit tasks
2019-03-14 13:17:41.787995: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:17:41.803669: wfastcgi.py 3.0.0 initialized
2019-03-14 13:17:49.291287: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 13:17:49.292285: Running on_exit tasks
2019-03-14 13:18:18.727149: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:18:18.727149: wfastcgi.py 3.0.0 initialized
2019-03-14 13:18:34.617988: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 13:18:34.617988: Running on_exit tasks
2019-03-14 13:18:48.855246: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:18:48.855246: wfastcgi.py 3.0.0 initialized
2019-03-14 13:19:41.308609: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 13:19:41.308609: Running on_exit tasks
2019-03-14 13:20:06.615170: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:20:06.618173: wfastcgi.py 3.0.0 initialized
2019-03-14 13:23:01.011594: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 13:23:01.011594: Running on_exit tasks
2019-03-14 13:23:08.679488: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:23:08.679488: wfastcgi.py 3.0.0 initialized
2019-03-14 13:30:07.768221: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-14 13:30:07.769222: Running on_exit tasks
2019-03-14 13:30:07.770224: wfastcgi.py 3.0.0 closed
2019-03-14 13:31:00.260273: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:31:00.262272: wfastcgi.py 3.0.0 initialized
2019-03-14 13:33:13.476037: wfastcgi.py exiting because report.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 13:33:13.476037: Running on_exit tasks
2019-03-14 13:34:33.483332: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 13:34:33.486333: wfastcgi.py 3.0.0 initialized
2019-03-14 13:40:57.239005: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-14 13:40:57.239005: Running on_exit tasks
2019-03-14 13:40:57.239005: wfastcgi.py 3.0.0 closed
2019-03-14 15:33:47.493473: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 15:33:47.494472: wfastcgi.py 3.0.0 initialized
2019-03-14 15:34:29.017819: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 15:34:29.020812: wfastcgi.py 3.0.0 initialized
2019-03-14 15:36:05.895449: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-14 15:36:05.896452: Running on_exit tasks
2019-03-14 15:36:20.274002: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 15:36:20.275003: wfastcgi.py 3.0.0 initialized
2019-03-14 15:36:59.196754: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 15:36:59.197755: wfastcgi.py 3.0.0 initialized
2019-03-14 15:36:59.216809: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-14 15:36:59.218804: wfastcgi.py 3.0.0 initialized
2019-03-14 15:42:09.065351: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-14 15:42:09.066350: Running on_exit tasks
2019-03-14 15:42:09.067350: wfastcgi.py 3.0.0 closed
2019-03-14 15:42:13.223150: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-14 15:42:13.224151: Running on_exit tasks
2019-03-14 15:42:13.225150: wfastcgi.py 3.0.0 closed
2019-03-14 15:42:13.254150: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-14 15:42:13.255151: Running on_exit tasks
2019-03-14 15:42:13.256151: wfastcgi.py 3.0.0 closed
2019-03-17 21:57:27.998003: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 21:57:28.001007: wfastcgi.py 3.0.0 initialized
2019-03-17 21:57:29.719066: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 21:57:29.721134: wfastcgi.py 3.0.0 initialized
2019-03-17 21:57:29.743068: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 21:57:29.745068: wfastcgi.py 3.0.0 initialized
2019-03-17 21:57:29.779068: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 21:57:29.789069: wfastcgi.py 3.0.0 initialized
2019-03-17 21:58:47.623517: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 21:58:47.624520: wfastcgi.py 3.0.0 initialized
2019-03-17 22:06:56.785393: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-17 22:06:56.785393: Running on_exit tasks
2019-03-17 22:06:56.785393: wfastcgi.py 3.0.0 closed
2019-03-17 22:32:25.001159: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 8, in <module>
    import remote_execution_expect
  File ".\remote_execution_expect.py", line 204
    execution_output[device_address]['output'] +=
                                                ^
SyntaxError: invalid syntax


StdOut: 

StdErr: 
2019-03-17 22:38:20.924141: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 22:38:20.925849: wfastcgi.py 3.0.0 initialized
2019-03-17 22:39:23.294789: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-17 22:39:23.301790: Running on_exit tasks
2019-03-17 23:17:44.030982: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 23:17:44.030982: wfastcgi.py 3.0.0 initialized
2019-03-17 23:18:32.150759: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-17 23:18:32.150759: Running on_exit tasks
2019-03-17 23:23:11.972286: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 23:23:11.978284: wfastcgi.py 3.0.0 initialized
2019-03-17 23:29:35.546302: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-17 23:29:35.548301: Running on_exit tasks
2019-03-17 23:29:35.549301: wfastcgi.py 3.0.0 closed
2019-03-17 23:36:21.628701: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-17 23:36:21.630699: wfastcgi.py 3.0.0 initialized
2019-03-18 00:11:16.741475: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-18 00:11:16.754004: Running on_exit tasks
2019-03-18 00:12:18.701499: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-18 00:12:18.703500: wfastcgi.py 3.0.0 initialized
2019-03-18 00:23:57.583394: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-18 00:23:57.583394: Running on_exit tasks
2019-03-18 00:23:57.583394: wfastcgi.py 3.0.0 closed
2019-03-20 10:41:58.702846: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 10:41:58.718481: wfastcgi.py 3.0.0 initialized
2019-03-20 10:43:30.282701: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 10:43:30.283703: Running on_exit tasks
2019-03-20 10:46:18.304091: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 10:46:18.306089: wfastcgi.py 3.0.0 initialized
2019-03-20 10:52:41.923555: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-20 10:52:41.923555: Running on_exit tasks
2019-03-20 10:52:41.923555: wfastcgi.py 3.0.0 closed
2019-03-20 15:30:22.927165: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 15:30:22.927165: wfastcgi.py 3.0.0 initialized
2019-03-20 15:37:58.739918: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 15:37:58.741919: Running on_exit tasks
2019-03-20 15:38:21.190245: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 15:38:21.192246: wfastcgi.py 3.0.0 initialized
2019-03-20 15:43:34.924465: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-20 15:43:34.925556: Running on_exit tasks
2019-03-20 15:43:34.926463: wfastcgi.py 3.0.0 closed
2019-03-20 15:49:04.142839: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 15:49:04.143841: wfastcgi.py 3.0.0 initialized
2019-03-20 15:54:25.974847: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 15:54:25.975847: Running on_exit tasks
2019-03-20 15:57:28.904960: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 15:57:28.905959: wfastcgi.py 3.0.0 initialized
2019-03-20 16:05:02.841377: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-20 16:05:02.841377: Running on_exit tasks
2019-03-20 16:05:02.841377: wfastcgi.py 3.0.0 closed
2019-03-20 16:30:42.122007: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:30:42.122007: wfastcgi.py 3.0.0 initialized
2019-03-20 16:31:09.960027: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:31:09.961026: Running on_exit tasks
2019-03-20 16:31:15.212163: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:31:15.212163: wfastcgi.py 3.0.0 initialized
2019-03-20 16:31:41.837519: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:31:41.837519: Running on_exit tasks
2019-03-20 16:31:53.415082: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:31:53.415082: wfastcgi.py 3.0.0 initialized
2019-03-20 16:32:11.886390: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:32:11.886390: Running on_exit tasks
2019-03-20 16:32:29.933869: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:32:29.933869: wfastcgi.py 3.0.0 initialized
2019-03-20 16:32:53.481889: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:32:53.481889: Running on_exit tasks
2019-03-20 16:32:59.463303: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:32:59.464304: wfastcgi.py 3.0.0 initialized
2019-03-20 16:33:32.701124: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:33:32.702125: Running on_exit tasks
2019-03-20 16:33:39.696381: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:33:39.698381: wfastcgi.py 3.0.0 initialized
2019-03-20 16:34:39.720321: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:34:39.735945: Running on_exit tasks
2019-03-20 16:34:50.987231: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:34:50.987231: wfastcgi.py 3.0.0 initialized
2019-03-20 16:35:09.438900: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:35:09.438900: Running on_exit tasks
2019-03-20 16:35:18.863090: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:35:18.863090: wfastcgi.py 3.0.0 initialized
2019-03-20 16:37:01.174553: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 16:37:01.174553: Running on_exit tasks
2019-03-20 16:37:10.262620: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 16:37:10.263691: wfastcgi.py 3.0.0 initialized
2019-03-20 16:47:39.369204: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-20 16:47:39.369204: Running on_exit tasks
2019-03-20 16:47:39.369204: wfastcgi.py 3.0.0 closed
2019-03-20 20:23:01.002748: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:23:01.002748: wfastcgi.py 3.0.0 initialized
2019-03-20 20:25:29.380637: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:25:29.381637: Running on_exit tasks
2019-03-20 20:25:46.227902: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:25:46.227902: wfastcgi.py 3.0.0 initialized
2019-03-20 20:25:52.366290: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:25:52.366290: Running on_exit tasks
2019-03-20 20:26:15.118250: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:26:15.118250: wfastcgi.py 3.0.0 initialized
2019-03-20 20:26:35.062740: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:26:35.063740: Running on_exit tasks
2019-03-20 20:26:40.752353: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:26:40.752353: wfastcgi.py 3.0.0 initialized
2019-03-20 20:26:58.364243: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:26:58.365242: Running on_exit tasks
2019-03-20 20:27:04.379349: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:27:04.395689: wfastcgi.py 3.0.0 initialized
2019-03-20 20:27:13.844538: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:27:13.844538: Running on_exit tasks
2019-03-20 20:27:42.683264: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:27:42.683264: wfastcgi.py 3.0.0 initialized
2019-03-20 20:27:53.270315: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:27:53.271315: Running on_exit tasks
2019-03-20 20:36:28.862425: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 20:36:28.866424: wfastcgi.py 3.0.0 initialized
2019-03-20 20:40:44.775401: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 20:40:44.776401: Running on_exit tasks
2019-03-20 22:00:30.672198: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 22:00:30.674203: wfastcgi.py 3.0.0 initialized
2019-03-20 22:06:54.541488: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-20 22:06:54.541488: Running on_exit tasks
2019-03-20 22:06:54.541488: wfastcgi.py 3.0.0 closed
2019-03-20 22:16:59.824752: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-20 22:16:59.827751: wfastcgi.py 3.0.0 initialized
2019-03-20 22:21:43.152899: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-20 22:21:43.152899: Running on_exit tasks
2019-03-21 11:36:45.734028: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-21 11:36:45.756023: wfastcgi.py 3.0.0 initialized
2019-03-21 11:44:51.686069: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-21 11:44:51.686069: Running on_exit tasks
2019-03-21 11:44:51.686069: wfastcgi.py 3.0.0 closed
2019-03-21 11:51:09.494531: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-21 11:51:09.494531: wfastcgi.py 3.0.0 initialized
2019-03-21 11:56:23.360359: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-21 11:56:23.361539: Running on_exit tasks
2019-03-21 11:56:23.362551: wfastcgi.py 3.0.0 closed
2019-03-25 15:39:06.299997: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-25 15:39:06.299997: wfastcgi.py 3.0.0 initialized
2019-03-25 15:49:25.026418: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-25 15:49:25.026418: Running on_exit tasks
2019-03-25 15:49:25.026418: wfastcgi.py 3.0.0 closed
2019-03-25 16:13:43.465719: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-25 16:13:43.465719: wfastcgi.py 3.0.0 initialized
2019-03-25 16:22:26.219410: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-25 16:22:26.219410: Running on_exit tasks
2019-03-25 16:22:26.219410: wfastcgi.py 3.0.0 closed
2019-03-25 16:24:04.476420: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-25 16:24:04.478420: wfastcgi.py 3.0.0 initialized
2019-03-25 16:29:18.232969: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-25 16:29:18.234972: Running on_exit tasks
2019-03-25 16:29:18.235967: wfastcgi.py 3.0.0 closed
2019-03-25 17:13:45.618843: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-25 17:13:45.618843: wfastcgi.py 3.0.0 initialized
2019-03-25 17:18:58.865719: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-25 17:18:58.866719: Running on_exit tasks
2019-03-25 17:18:58.867719: wfastcgi.py 3.0.0 closed
2019-03-25 21:42:58.710406: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-25 21:42:58.710406: wfastcgi.py 3.0.0 initialized
2019-03-25 21:49:21.726453: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-25 21:49:21.728453: Running on_exit tasks
2019-03-25 21:49:21.729452: wfastcgi.py 3.0.0 closed
2019-03-25 21:50:00.550064: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-25 21:50:00.552079: wfastcgi.py 3.0.0 initialized
2019-03-25 21:58:43.953996: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-25 21:58:43.954995: Running on_exit tasks
2019-03-25 21:58:43.955993: wfastcgi.py 3.0.0 closed
2019-03-26 08:58:58.103435: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 08:58:58.115457: wfastcgi.py 3.0.0 initialized
2019-03-26 08:58:59.875210: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 08:58:59.877216: wfastcgi.py 3.0.0 initialized
2019-03-26 08:58:59.955210: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 08:58:59.957210: wfastcgi.py 3.0.0 initialized
2019-03-26 08:58:59.978213: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 08:58:59.983218: wfastcgi.py 3.0.0 initialized
2019-03-26 09:03:59.136430: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:03:59.136430: Running on_exit tasks
2019-03-26 09:03:59.136430: wfastcgi.py 3.0.0 closed
2019-03-26 09:04:13.616324: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:04:13.616324: Running on_exit tasks
2019-03-26 09:04:13.616324: wfastcgi.py 3.0.0 closed
2019-03-26 09:04:13.647578: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:04:13.647578: Running on_exit tasks
2019-03-26 09:04:13.647578: wfastcgi.py 3.0.0 closed
2019-03-26 09:04:13.678831: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:04:13.678831: Running on_exit tasks
2019-03-26 09:04:13.678831: wfastcgi.py 3.0.0 closed
2019-03-26 09:05:18.093755: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:05:18.094740: wfastcgi.py 3.0.0 initialized
2019-03-26 09:14:02.059112: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:14:02.059112: Running on_exit tasks
2019-03-26 09:14:02.059112: wfastcgi.py 3.0.0 closed
2019-03-26 09:24:12.237954: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:24:12.240009: wfastcgi.py 3.0.0 initialized
2019-03-26 09:31:11.183975: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:31:11.183975: Running on_exit tasks
2019-03-26 09:31:11.183975: wfastcgi.py 3.0.0 closed
2019-03-26 09:33:15.586006: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:33:15.586965: wfastcgi.py 3.0.0 initialized
2019-03-26 09:33:27.509581: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 09:33:27.510582: Running on_exit tasks
2019-03-26 09:33:31.878654: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:33:31.880652: wfastcgi.py 3.0.0 initialized
2019-03-26 09:34:01.893568: wfastcgi.py exiting because app.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 09:34:01.894568: Running on_exit tasks
2019-03-26 09:35:52.871209: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:35:52.873211: wfastcgi.py 3.0.0 initialized
2019-03-26 09:38:03.727028: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:38:03.729028: wfastcgi.py 3.0.0 initialized
2019-03-26 09:38:03.810029: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:38:03.812029: wfastcgi.py 3.0.0 initialized
2019-03-26 09:38:03.827028: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:38:03.830028: wfastcgi.py 3.0.0 initialized
2019-03-26 09:43:17.286212: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:43:17.288216: Running on_exit tasks
2019-03-26 09:43:17.289217: wfastcgi.py 3.0.0 closed
2019-03-26 09:43:17.385180: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:43:17.387181: Running on_exit tasks
2019-03-26 09:43:17.388180: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:43:17.391180: Running on_exit tasks
2019-03-26 09:43:17.392180: wfastcgi.py 3.0.0 closed
2019-03-26 09:43:26.847768: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:43:26.848716: Running on_exit tasks
2019-03-26 09:43:26.849715: wfastcgi.py 3.0.0 closed
2019-03-26 09:54:11.775557: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 09:54:11.777550: wfastcgi.py 3.0.0 initialized
2019-03-26 09:59:25.724328: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 09:59:25.724328: Running on_exit tasks
2019-03-26 09:59:25.724328: wfastcgi.py 3.0.0 closed
2019-03-26 10:00:53.493854: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:00:53.496258: wfastcgi.py 3.0.0 initialized
2019-03-26 10:07:17.273201: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:07:17.273201: Running on_exit tasks
2019-03-26 10:07:17.273201: wfastcgi.py 3.0.0 closed
2019-03-26 10:15:44.601428: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:15:44.603428: wfastcgi.py 3.0.0 initialized
2019-03-26 10:20:58.549293: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:20:58.549293: Running on_exit tasks
2019-03-26 10:20:58.549293: wfastcgi.py 3.0.0 closed
2019-03-26 10:21:30.204614: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:21:30.205617: wfastcgi.py 3.0.0 initialized
2019-03-26 10:26:44.296691: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:26:44.296691: Running on_exit tasks
2019-03-26 10:26:44.296691: wfastcgi.py 3.0.0 closed
2019-03-26 10:27:09.576684: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:27:09.580338: wfastcgi.py 3.0.0 initialized
2019-03-26 10:31:32.117409: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:31:32.119410: wfastcgi.py 3.0.0 initialized
2019-03-26 10:31:32.144411: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:31:32.146410: wfastcgi.py 3.0.0 initialized
2019-03-26 10:31:32.204408: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:31:32.207407: wfastcgi.py 3.0.0 initialized
2019-03-26 10:36:46.003675: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:36:46.034861: Running on_exit tasks
2019-03-26 10:36:46.034861: wfastcgi.py 3.0.0 closed
2019-03-26 10:36:46.081739: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:36:46.081739: Running on_exit tasks
2019-03-26 10:36:46.081739: wfastcgi.py 3.0.0 closed
2019-03-26 10:37:03.067228: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:37:03.067228: Running on_exit tasks
2019-03-26 10:37:03.067228: wfastcgi.py 3.0.0 closed
2019-03-26 10:42:01.007110: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:42:01.007110: Running on_exit tasks
2019-03-26 10:42:01.007110: wfastcgi.py 3.0.0 closed
2019-03-26 10:46:10.551916: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:46:10.552916: wfastcgi.py 3.0.0 initialized
2019-03-26 10:51:24.546286: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 10:51:24.546286: Running on_exit tasks
2019-03-26 10:51:24.546286: wfastcgi.py 3.0.0 closed
2019-03-26 10:57:24.962668: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:57:24.962668: wfastcgi.py 3.0.0 initialized
2019-03-26 10:57:24.997262: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 10:57:24.999269: wfastcgi.py 3.0.0 initialized
2019-03-26 11:02:38.821154: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 11:02:38.821154: Running on_exit tasks
2019-03-26 11:02:38.821154: wfastcgi.py 3.0.0 closed
2019-03-26 11:05:33.823498: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 11:05:33.823498: Running on_exit tasks
2019-03-26 11:05:33.823498: wfastcgi.py 3.0.0 closed
2019-03-26 11:07:07.611584: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:07:07.611584: wfastcgi.py 3.0.0 initialized
2019-03-26 11:07:07.745554: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:07:07.745554: wfastcgi.py 3.0.0 initialized
2019-03-26 11:12:21.280595: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 11:12:21.280595: Running on_exit tasks
2019-03-26 11:12:21.280595: wfastcgi.py 3.0.0 closed
2019-03-26 11:14:06.293424: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 11:14:06.293424: Running on_exit tasks
2019-03-26 11:14:06.293424: wfastcgi.py 3.0.0 closed
2019-03-26 11:14:12.326451: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:14:12.342025: wfastcgi.py 3.0.0 initialized
2019-03-26 11:18:14.560973: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:18:14.561973: Running on_exit tasks
2019-03-26 11:19:21.619513: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:19:21.626515: wfastcgi.py 3.0.0 initialized
2019-03-26 11:23:05.007340: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:23:05.008341: Running on_exit tasks
2019-03-26 11:23:59.299398: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:23:59.299398: wfastcgi.py 3.0.0 initialized
2019-03-26 11:25:50.814196: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:25:50.815196: Running on_exit tasks
2019-03-26 11:27:14.394624: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:27:14.394624: wfastcgi.py 3.0.0 initialized
2019-03-26 11:29:04.161189: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:29:04.161189: Running on_exit tasks
2019-03-26 11:30:01.927435: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:30:01.928428: wfastcgi.py 3.0.0 initialized
2019-03-26 11:30:47.924807: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:30:47.924807: Running on_exit tasks
2019-03-26 11:31:18.779274: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:31:18.780272: wfastcgi.py 3.0.0 initialized
2019-03-26 11:33:49.509949: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:33:49.510947: Running on_exit tasks
2019-03-26 11:49:28.552438: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:49:28.552438: wfastcgi.py 3.0.0 initialized
2019-03-26 11:50:21.350305: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:50:21.351306: Running on_exit tasks
2019-03-26 11:51:04.367303: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:51:04.369304: wfastcgi.py 3.0.0 initialized
2019-03-26 11:52:31.838486: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:52:31.839487: Running on_exit tasks
2019-03-26 11:57:12.684000: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 11:57:12.686001: wfastcgi.py 3.0.0 initialized
2019-03-26 11:59:05.724610: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 11:59:05.725611: Running on_exit tasks
2019-03-26 12:07:43.596114: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 12:07:43.596114: wfastcgi.py 3.0.0 initialized
2019-03-26 12:11:22.911116: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 12:11:22.911116: Running on_exit tasks
2019-03-26 12:39:33.468762: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 12:39:33.469761: wfastcgi.py 3.0.0 initialized
2019-03-26 12:42:49.939757: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 12:42:49.940757: Running on_exit tasks
2019-03-26 12:43:15.214403: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 12:43:15.216402: wfastcgi.py 3.0.0 initialized
2019-03-26 12:48:29.065239: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 12:48:29.065239: Running on_exit tasks
2019-03-26 12:48:29.065239: wfastcgi.py 3.0.0 closed
2019-03-26 14:47:57.438694: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 14:47:57.440694: wfastcgi.py 3.0.0 initialized
2019-03-26 14:48:25.444788: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 14:48:25.445788: wfastcgi.py 3.0.0 initialized
2019-03-26 14:53:08.222418: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 14:53:08.222418: Running on_exit tasks
2019-03-26 14:53:08.256330: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 14:53:08.258331: Running on_exit tasks
2019-03-26 14:54:57.107414: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 14:54:57.110414: wfastcgi.py 3.0.0 initialized
2019-03-26 14:56:24.640134: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 14:56:24.641132: Running on_exit tasks
2019-03-26 14:56:40.913164: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 14:56:40.915171: wfastcgi.py 3.0.0 initialized
2019-03-26 15:01:54.744784: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 15:01:54.744784: Running on_exit tasks
2019-03-26 15:01:54.744784: wfastcgi.py 3.0.0 closed
2019-03-26 15:38:20.984364: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 15:38:20.987341: wfastcgi.py 3.0.0 initialized
2019-03-26 15:38:53.665035: wfastcgi.py exiting because run_single_device.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 15:38:53.666036: Running on_exit tasks
2019-03-26 15:39:03.047816: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 15:39:03.048819: wfastcgi.py 3.0.0 initialized
2019-03-26 15:44:51.891828: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 15:44:51.891828: Running on_exit tasks
2019-03-26 15:44:51.891828: wfastcgi.py 3.0.0 closed
2019-03-26 15:45:56.640102: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 15:45:56.641103: wfastcgi.py 3.0.0 initialized
2019-03-26 15:47:25.587552: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 15:47:25.588552: Running on_exit tasks
2019-03-26 15:48:38.891666: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 15:48:38.892668: wfastcgi.py 3.0.0 initialized
2019-03-26 15:54:27.663240: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 15:54:27.663240: Running on_exit tasks
2019-03-26 15:54:27.663240: wfastcgi.py 3.0.0 closed
2019-03-26 15:55:10.590100: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 15:55:10.590100: wfastcgi.py 3.0.0 initialized
2019-03-26 15:55:10.670107: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 15:55:10.675103: wfastcgi.py 3.0.0 initialized
2019-03-26 16:00:24.345387: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:00:24.345387: Running on_exit tasks
2019-03-26 16:00:24.345387: wfastcgi.py 3.0.0 closed
2019-03-26 16:00:24.392214: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:00:24.392214: Running on_exit tasks
2019-03-26 16:00:24.392214: wfastcgi.py 3.0.0 closed
2019-03-26 16:05:10.285455: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:05:10.286459: wfastcgi.py 3.0.0 initialized
2019-03-26 16:05:10.338459: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:05:10.340461: wfastcgi.py 3.0.0 initialized
2019-03-26 16:10:23.586833: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:10:23.587917: Running on_exit tasks
2019-03-26 16:10:23.588789: wfastcgi.py 3.0.0 closed
2019-03-26 16:10:58.633771: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:10:58.634805: Running on_exit tasks
2019-03-26 16:10:58.635804: wfastcgi.py 3.0.0 closed
2019-03-26 16:11:15.198741: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:11:15.200742: wfastcgi.py 3.0.0 initialized
2019-03-26 16:16:09.220509: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:16:09.236134: wfastcgi.py 3.0.0 initialized
2019-03-26 16:20:55.495918: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 16:20:55.495918: Running on_exit tasks
2019-03-26 16:20:55.530556: wfastcgi.py exiting because remote_execution_expect.py has changed, matching .*((\.py)|(\.config))$
2019-03-26 16:20:55.531557: Running on_exit tasks
2019-03-26 16:21:07.772717: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:21:07.774653: wfastcgi.py 3.0.0 initialized
2019-03-26 16:31:01.572482: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:31:01.572482: Running on_exit tasks
2019-03-26 16:31:01.572482: wfastcgi.py 3.0.0 closed
2019-03-26 16:34:36.293879: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:34:36.293879: wfastcgi.py 3.0.0 initialized
2019-03-26 16:34:36.318938: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:34:36.320933: wfastcgi.py 3.0.0 initialized
2019-03-26 16:39:50.290227: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:39:50.290227: Running on_exit tasks
2019-03-26 16:39:50.290227: wfastcgi.py 3.0.0 closed
2019-03-26 16:43:42.029043: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:43:42.029043: wfastcgi.py 3.0.0 initialized
2019-03-26 16:43:49.137456: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:43:49.137456: wfastcgi.py 3.0.0 initialized
2019-03-26 16:43:49.184266: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-03-26 16:43:49.184266: wfastcgi.py 3.0.0 initialized
2019-03-26 16:48:56.079829: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:48:56.079829: Running on_exit tasks
2019-03-26 16:48:56.079829: wfastcgi.py 3.0.0 closed
2019-03-26 16:49:03.135202: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:49:03.135202: Running on_exit tasks
2019-03-26 16:49:03.135202: wfastcgi.py 3.0.0 closed
2019-03-26 16:49:10.297099: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:49:10.297099: Running on_exit tasks
2019-03-26 16:49:10.297099: wfastcgi.py 3.0.0 closed
2019-03-26 16:53:43.131177: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-03-26 16:53:43.131177: Running on_exit tasks
2019-03-26 16:53:43.131177: wfastcgi.py 3.0.0 closed
2019-04-17 11:23:56.311189: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-17 11:23:56.313204: wfastcgi.py 3.0.0 initialized
2019-04-17 11:23:58.049913: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-17 11:23:58.051923: wfastcgi.py 3.0.0 initialized
2019-04-17 11:23:58.073960: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-17 11:23:58.075001: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-17 11:23:58.076914: wfastcgi.py 3.0.0 initialized
2019-04-17 11:23:58.077915: wfastcgi.py 3.0.0 initialized
2019-04-17 11:28:59.015093: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-17 11:28:59.015093: Running on_exit tasks
2019-04-17 11:28:59.015093: wfastcgi.py 3.0.0 closed
2019-04-17 11:29:11.777752: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-17 11:29:11.777752: Running on_exit tasks
2019-04-17 11:29:11.777752: wfastcgi.py 3.0.0 closed
2019-04-17 11:29:11.808994: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-17 11:29:11.808994: Running on_exit tasks
2019-04-17 11:29:11.808994: wfastcgi.py 3.0.0 closed
2019-04-17 11:29:11.840195: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-17 11:29:11.840195: Running on_exit tasks
2019-04-17 11:29:11.840195: wfastcgi.py 3.0.0 closed
2019-04-25 12:58:50.776731: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-25 12:58:50.778708: wfastcgi.py 3.0.0 initialized
2019-04-25 12:58:53.089291: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-25 12:58:53.091290: wfastcgi.py 3.0.0 initialized
2019-04-25 12:58:53.161289: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-25 12:58:53.163290: wfastcgi.py 3.0.0 initialized
2019-04-25 12:58:53.178290: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-04-25 12:58:53.181291: wfastcgi.py 3.0.0 initialized
2019-04-25 13:04:06.741079: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-25 13:04:06.742080: Running on_exit tasks
2019-04-25 13:04:06.744077: wfastcgi.py 3.0.0 closed
2019-04-25 13:04:06.822077: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-25 13:04:06.823077: Running on_exit tasks
2019-04-25 13:04:06.823077: wfastcgi.py 3.0.0 closed
2019-04-25 13:04:21.170302: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-25 13:04:21.170302: Running on_exit tasks
2019-04-25 13:04:21.170302: wfastcgi.py 3.0.0 closed
2019-04-25 13:08:46.750495: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-04-25 13:08:46.760495: Running on_exit tasks
2019-04-25 13:08:46.762518: wfastcgi.py 3.0.0 closed
2019-04-30 18:35:12.895275: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 9, in <module>
    import upgrade_firmware
  File ".\upgrade_firmware.py", line 65
    conn.commit()
    ^
IndentationError: unexpected indent


StdOut: 

StdErr: 
2019-04-30 18:35:13.818860: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 9, in <module>
    import upgrade_firmware
  File ".\upgrade_firmware.py", line 65
    conn.commit()
    ^
IndentationError: unexpected indent


StdOut: 

StdErr: 
2019-04-30 18:35:13.818860: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 9, in <module>
    import upgrade_firmware
  File ".\upgrade_firmware.py", line 65
    conn.commit()
    ^
IndentationError: unexpected indent
2019-04-30 18:38:06.152054: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 9, in <module>
    import upgrade_firmware
  File ".\upgrade_firmware.py", line 65
    conn.commit()
    ^
IndentationError: unexpected indent


StdOut: 

StdErr: 
2019-04-30 18:38:06.611273: Error occurred while reading WSGI handler:

Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 791, in main
    env, handler = read_wsgi_handler(response.physical_path)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 633, in read_wsgi_handler
    handler = get_wsgi_handler(os.getenv("WSGI_HANDLER"))
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 600, in get_wsgi_handler
    handler = __import__(module_name, fromlist=[name_list[0][0]])
  File ".\app.py", line 9, in <module>
    import upgrade_firmware
  File ".\upgrade_firmware.py", line 65
    conn.commit()
    ^
IndentationError: unexpected indent


StdOut: 

StdErr: 
2019-05-07 15:08:26.753396: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-05-07 15:08:26.755821: wfastcgi.py 3.0.0 initialized
2019-05-07 15:08:29.250981: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-05-07 15:08:29.253980: wfastcgi.py 3.0.0 initialized
2019-05-07 15:08:29.286982: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-05-07 15:08:29.289983: wfastcgi.py 3.0.0 initialized
2019-05-07 15:08:29.318985: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-05-07 15:08:29.321985: wfastcgi.py 3.0.0 initialized
2019-05-07 15:13:29.075786: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-05-07 15:13:29.076855: Running on_exit tasks
2019-05-07 15:13:29.078782: wfastcgi.py 3.0.0 closed
2019-05-07 15:13:42.610960: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-05-07 15:13:42.611961: Running on_exit tasks
2019-05-07 15:13:42.612958: wfastcgi.py 3.0.0 closed
2019-05-07 15:13:42.648960: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-05-07 15:13:42.648960: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-05-07 15:13:42.653964: Running on_exit tasks
2019-05-07 15:13:42.655964: wfastcgi.py 3.0.0 closed
2019-05-07 15:13:42.656960: wfastcgi.py 3.0.0 closed
2019-05-14 10:58:03.243800: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-05-14 10:58:03.255796: wfastcgi.py 3.0.0 initialized
2019-05-14 10:58:05.597898: wfastcgi.py will restart when files in C:\network_automation\python\ are changed: .*((\.py)|(\.config))$
2019-05-14 10:58:05.598899: wfastcgi.py 3.0.0 initialized
2019-05-14 11:03:41.005654: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-05-14 11:03:41.007654: Running on_exit tasks
2019-05-14 11:03:41.008654: wfastcgi.py 3.0.0 closed
2019-05-14 11:03:54.043585: Unhandled exception in wfastcgi.py: Traceback (most recent call last):
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 774, in main
    record = read_fastcgi_record(fcgi_stream)
  File "c:\users\shubha.ks\appdata\local\programs\python\python36\lib\site-packages\wfastcgi.py", line 158, in read_fastcgi_record
    data = stream.read(8)     # read record
OSError: [Errno 22] Invalid argument
2019-05-14 11:03:54.045583: Running on_exit tasks
2019-05-14 11:03:54.046585: wfastcgi.py 3.0.0 closed
